// User Actions
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';
export const SET_NEXT_EXPLANATION_CARD = 'SET_NEXT_EXPLANATION_CARD'
export const FORCE_GIN_STRIPPING_RUN = 'FORCE_GIN_STRIPPING_RUN'
export const INTERFACE_FOR_GIN = 'INTERFACE_FOR_GIN'
export const INTERFACE_FOR_BIG_POT = 'INTERFACE_FOR_BIG_POT'
export const HIDE_CONTROL_BUTTONS = 'HIDE_CONTROL_BUTTONS'

// Fractional Still Actions
export const GET_FRACTIONAL_GRAPH_DATA = 'GET_FRACTIONAL_GRAPH_DATA'
export const GET_RUN_OVERVIEW = 'GET_RUN_OVERVIEW'

// Pot Still Actions
export const GET_HISTORICAL_GRAPH_DATA = 'GET_HISTORICAL_GRAPH_DATA';
export const GET_POT_GRAPH_DATA = 'GET_POT_GRAPH_DATA';
export const GET_POT_RUN_OVERVIEW = 'GET_POT_RUN_OVERVIEW';
